### ISSUE TITLE
3.1.0 breaks

### ISSUE THREAD

**Issue by daguej** [BlessCSS/gulp-bless#22]
After upgrading from 3.0.1 ➔ 3.1.0, my build fails with:

```
Error: no writecb in Transform class
       at afterTransform (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
       at TransformState.afterTransform (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
       at /tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/gulp-less/index.js:58:14
       at tryCatchReject (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/when/lib/makePromise.js:845:30)
       at runContinuation1 (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/when/lib/makePromise.js:804:4)
       at Rejected.when (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/when/lib/makePromise.js:625:4)
       at Pending.run (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/when/lib/makePromise.js:483:13)
       at Scheduler._drain (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/when/lib/Scheduler.js:62:19)
       at Scheduler.drain (/tmp/build_510b3f92e5dba9a1f90b72862d435a16/node_modules/when/lib/Scheduler.js:27:9)
       at nextTickCallbackWith0Args (node.js:420:9)
       at process._tickCallback (node.js:349:13)
```

**Comment by mwdelaneytwg** [comment]
I can report a similar problem.

    TypeError: Cannot call method 'reduce' of undefined
        at countRules (/path-to-project/node_modules/bless/lib/count.js:26:18)
        at count (/path-to-project/node_modules/bless/lib/count.js:44:14)
        at chunks$ (/path-to-project/node_modules/bless/lib/chunk.js:52:46)
        at tryCatch (/path-to-project/node_modules/babel-runtime/regenerator/runtime.js:72:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/path-to-project/node_modules/babel-runtime/regenerator/runtime.js:334:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/path-to-project/node_modules/babel-runtime/regenerator/runtime.js:105:21)
        at chunk (/path-to-project/node_modules/bless/lib/chunk.js:98:113)
        at Object.chunk (/path-to-project/node_modules/bless/lib/index.js:34:33)
        at Transform._transform (/path-to-project/node_modules/gulp-bless/index.js:33:36)
        at Transform._read (/path-to-project/node_modules/gulp-bless/node_modules/readable-stream/lib/_stream_transform.js:184:10)

**Comment by RedLucas** [comment]
For what it's worth, I have run into both of these problems. I'm not sure what the issue is, but it's definitely causing issues.

**Comment by yvanavermaet** [comment]
I believe the problem is that gulp-bless uses bless v4 since version 3.1.0. The gulp-bless should have gone from 3.0.1 to 4.0.1 because bless v4 introduces a breaking change.

Either stick with 3.0.1 or investigate your set-up (check what bless v4 has changed in regards to bless v3)

**Comment by yvanavermaet** [comment]
Btw, for reference. It's a bless issue: https://github.com/BlessCSS/bless/issues/93

**Comment by scott-rothman** [comment]
I too am having the 'TypeError: Cannot call method 'reduce' of undefined'

I'm going try going with an older version that uses an older version of bless and see what I can come up with

**Comment by scott-rothman** [comment]
Installing gulp-bless 3.0.1 seems to work fine

**Comment by mtscout6** [comment]
v4.0.1 of Bless was just release that should fix this. Can someone that uses this confirm?

**Comment by scott-rothman** [comment]
@mtscout6 Looks good to me

**Comment by scott-rothman** [comment]
Actually, I take that back, I have verbose on and it spit out the following message

`Found 4386 selector, not splitting.`

It should split when above 4095

**Comment by adam-lynch** [comment]
Great
